### PR TITLE
Fixes loss of accuracy when rounding

### PR DESCRIPTION
**Pull request by limyz**
Fixes issue #11 due to truncation of decimal values

### CODE REVIEW

**Comment by DTXMania** [comment]
Thank you for your advice!

In the BemaniWiki, it says that the achievement rate is not rounding off the numbers, but truncating them.

http://bemaniwiki.com/index.php?GITADORA/%B4%F0%C1%C3%C3%CE%BC%B1#o7346883

Is this information out of date?

**Comment by limyz** [comment]
I don't think its out of date, the phrase combo did introduced some changes but it shouldn't affect old XG scoring.
http://bemaniwiki.com/index.php?GuitarFreaksXG%A1%F5DrumManiaXG/%A5%C6%A5%AF%A5%CB%A5%AB%A5%EB%A5%B9%A5%C6%A1%BC%A5%BF%A5%B9

See [DTXManiaNX's implementation on line 1429 in CScoreIni.cs](https://github.com/limyz/DTXmaniaNX/blob/1f9475cd2b960c2d2c90f3a4ae40a68852e4daa1/DTXMania/Code/Score%2CSong/CScoreIni.cs#L1429).

**Comment by DTXMania** [comment]
Even in that XG skill achievement calculation, it is written to truncate to the third decimal place....

> (DM)PERFECT率*0.85+GREAT率*0.35+COMBO率*0.15
> この式で用いる比率はリザルト画面上の整数値ではなく判定の個数÷総判定数の小数点第4位(%表記した場合の**第2位**)までの値を用いる
> 最終的な計算結果も小数点第2位までの(**第3位を切り捨てた**)値となる

**Comment by limyz** [comment]
image
It seems either rounding down or truncating the 3 digit is the correct implementation. I tested DTXMania2 with a song difficulty of 5 and it reflects the correct skill point calculation of 100.00 points on the UI. We probably will need more testing to confirm this.

**Comment by fisyher** [comment]
I believe the game does actually truncate to 2 decimal places. Internally, numbers with 2 decimal places are actually stored as integers after multiplying by 100. So 88.30% is stored as 8830 and 155.40 is stored as 15540 and so on.

**Comment by DTXMania** [comment]
On October 14, 2019, I rebuilt all of DTXMania2 using C# 8.0 and .NET Core 3.0.

Before rebuilding, I used Math.Floor() for truncation in '_小数点第3位以下切り捨て()' method.
After rebuilding, it has been replaced by Math.Truncate().

So, the issue #11 had already been resolved.
I'm very sorry.

**Pull request closed without merging**
